Keyring config and datafile minor UX improvements (#24)
1. If tde config file is writable to DB it shouldn't prevent its loading.

2. If keyringCheckConfigFile() returns 0, config won't be loaded. Hence
keyringAssignConfigFile() and all its checks will be omitted. And user
gonna get a bit confusing error at the access of tde table:
```
PANIC:  Couldn't write keyring data:
```
So added check if keyringFileDataFileName is set. And the error now:
```
ERROR:  Keyring datafile is not set
```

3. Add quote marks around file names in log messages so it's easier to spot
if the file name is empty.
`Keyring file  not found, not loading existing keys.`
vs
`Keyring file '' not found, not loading existing keys.`