Make sure to detach injection points for re-attaching
The new test for enabling data checksums with concurrent CREATE
DATABASE calls use the same injection points as a previous test
but accidentally missed detaching the injection point first.

Fix by detaching the injection point in the PG_TEST_EXTRA SKIP
block to make it can be reused.  Pointed out by buildfarm member
porpoise which failed with:

    die: error running SQL: 'psql:<stdin>:1:
	     ERROR: injection point "datachecksumsworker-fake-temptable-wait"
		        already defined'

Backpatch to v19 where online checksums were introduced.

Author: Daniel Gustafsson <daniel@yesql.se>
Reported-by: Buildfarm member porpoise
Reviewed-by: Jonathan Gonzalez V. <jonathan.abdiel@gmail.com>
Discussion: https://postgr.es/m/28CF6FD9-E1C4-4C04-8270-E3305AC46171@yesql.se
Backpatch-through: 19